name: CD Workflow

on:
  push:

    branches: [ demo ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run unit tests
        run: |
          mvn clean test
      - name: Build jar
        run: |
          pwd
          mvn install -DskipTests
          pwd
          ls -al
          ls -al target
      - name: Build Deployment Artifact
        run: |
          pwd
          mkdir codedeploy_artifact
          zip -r csye6225-webapp-${{ github.run_number }}.zip target/webapp-0.0.1-SNAPSHOT.jar CodeDeploy/*.sh appspec.yml
          pwd
          ls -al
          mv csye6225-webapp-${{ github.run_number }}.zip codedeploy_artifact/
          cd codedeploy_artifact
          ls -al
      - name: copy to S3
        run: aws s3 cp codedeploy_artifact/csye6225-webapp-${{ github.run_number }}.zip s3://${{ secrets.AWS_BUCKET_PROVIDER }}.codedeploy.adityakamatcsye.me/csye6225-webapp-${{ github.run_number }}.zip
      - name: CodeDeploy API call
        run: |
          output=$(aws deploy create-deployment \
            --application-name "csye6225-webapp" \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name "csye6225-webapp-deployment" \
            --description "CSYE6225 - Codedeploy" \
            --s3-location bucket=${{ secrets.AWS_BUCKET_PROVIDER }}.codedeploy.adityakamatcsye.me,key=csye6225-webapp-${{ github.run_number }}.zip,bundleType=zip \
            --region us-east-1 \
            --output json)
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')

          aws deploy wait deployment-successful --deployment-id $dId



